version: "3.9"
services:
  app:
    build: ./cmd
    container_name: app
    environment:
      MYSQL_DATABASE: mental-app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: host.docker.internal:3306
    volumes:
      - ./cmd:/go/src/app
    tty: true
    ports:
      - 8080:8080